### ISSUE TITLE
text not visible in timestamps: text color is same as its background

### ISSUE THREAD

**Issue by RoguedBear** [Saltssaumure/ieytd-discord-theme#2]
timestamps look like this:
![image](https://user-images.githubusercontent.com/39442192/154787771-3f7bcc49-e95b-4bff-9e73-bdc76b584294.png)

adding `color: black` for class `timestamp-6-ptG3` fixes it
![image](https://user-images.githubusercontent.com/39442192/154787792-b23aadac-61cd-4478-85fc-c20634591d81.png)

![image](https://user-images.githubusercontent.com/39442192/154787816-ca5ed5b9-ede4-4268-9e02-275c831f2fe5.png)

**Comment by Saltssaumure** [comment]
Fixed now, thanks for letting me know. 
![image](https://user-images.githubusercontent.com/29710355/154855506-9efd18bd-fa40-458b-8882-6f21fff60167.png)
