### ISSUE TITLE
problem with role names

### ISSUE THREAD

**Issue by cxtieDollvp** [Saltssaumure/ieytd-discord-theme#5]
I downloaded your theme it's great. but there's a problem with the roles, when I went to the role section I saw the text is the same as the background color so you can't see the role's names and have to click on it to see the role name. it can be tedious when looking for a specific role. I think you can use colors two or three for the role names to fix it. thank you for seeing this.

**Comment by Saltssaumure** [comment]
Sorry about that, I haven't looked at this theme for a long while and looks like Discord changed a bunch of stuff in the background. I'll get round to fixing it hopefully today, maybe tomorrow.

**Comment by Saltssaumure** [comment]
Should be fixed now, sorry for the delay - ended up fixing half the rest of the theme too.
