### ISSUE TITLE
Issue with vencord's plugins

### ISSUE THREAD

**Issue by Lock-jawl** [Saltssaumure/ieytd-discord-theme#7]
There is an issue with vencord in the plugins section where the text of them is not visible.
![Screenshot_1](https://github.com/Saltssaumure/ieytd-discord-theme/assets/141946771/ed5fc024-f6ff-4e56-bdf3-bc3b0881268b)

**Comment by Lock-jawl** [comment]
Same thing goes for settings and for most of the roles but only if users don't have a different color of the background with nitro ( for what I can see)
![Screenshot_1](https://github.com/Saltssaumure/ieytd-discord-theme/assets/141946771/e4144ab5-5bce-4911-a6a5-51db640db5ac)

**Comment by Saltssaumure** [comment]
Should be fixed now in v2.0.1

**Comment by Lock-jawl** [comment]
Now there is no theme at all XD
I downloaded it and when I turn it on it's just grey discord, tho if I use the link raw of ieytd.min.css it does work
