### ISSUE TITLE
Cannot see usernames in voice chat

### ISSUE THREAD

**Issue by Lock-jawl** [Saltssaumure/ieytd-discord-theme#8]
Now there is no theme at all XD
I downloaded it and when I turn it on it's just grey discord, tho if I use the link raw of ieytd.min.css it does work

**Comment by Saltssaumure** [comment]
Redownload the theme file, it's a full-on rewrite hence the breaking changes.

**Comment by Lock-jawl** [comment]
I am downloading it from better discord but when I toggle it, it does not load... tried again just now

**Comment by Lock-jawl** [comment]
Ok I downloaded the correct file now it's working, but now you can't see the names of the users in some channels
